---
- name: Setup Flask API
  hosts: all
  become: yes 

  tasks:
    - name: Instalar dependências
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - virtualenv
        - gunicorn

    - name: Instalar Prometheus e Grafana
    hosts: all
    tasks:
      - name: Instalar Prometheus e Grafana
        apt:
          name: 
            - prometheus
            - grafana

    - name: Criar ambiente virtual
      command: virtualenv -p python3 venv
      args:
        chdir: /opt/app
      become_user: user
      become: yes

    - name: Ativar ambiente virtual e instalar dependências
      pip:
        requirements: requirements.txt
      args:
        chdir: /opt/app/app
      become_user: user
      become: yes

    - name: Iniciar aplicação usando Gunicorn
      command: gunicorn --log-level debug api:app
      args:
        chdir: /opt/app
      async: true
      poll: 0
